site_name: Alconium Docs
site_description: 'Provider APIs and technical details for Alconium'
site_author: 'Blake Leonard'
docs_dir: docs/
repo_name: 'alconium/docs'
repo_url: 'https://github.com/alconium/docs'
nav:
  - Home: index.md
theme:
  name: 'bootstrap'
  custom_dir: overrides/
